python3 -m unittest TestSubTypeTree_TDD.py
python3 -m unittest TestSubTypeTreeFactory_BlackBox.py
python3 -m unittest TestVenderTreeFactory_BlackBox.py
python3 -m unittest TestSubTypeTree_BlackBox.py
python3 -m unittest TestStandardTree_BlackBox.py
python3 -m unittest TestParsonalTree_BlackBox.py
python3 -m unittest TestUnregisteredTree_BlackBox.py
python3 -m unittest TestVenderTree_BlackBox.py
python3 -m unittest TestGitHubVenderTree_BlackBox.py
